### ISSUE TITLE
We can avoid using : there

### ISSUE THREAD

**Issue by mahbub02** [sadiashormin/python_problems#2]
https://github.com/sadiashormin/python_problems/blob/5c10ccf7c3c334d4e92f2c0dcc4399a4a4476f0a/capitalize.py#L2

**Comment by sadiashormin** [comment]
Good catch. Fixed it [here](https://github.com/sadiashormin/python_problems/commit/80a26fe2fe0b135ffa4730406637df70f42f4c54)
